import type { Difficulty, GameMode } from "@/lib/types";
import type { EntityEntry } from "@/lib/data/entities";
import {
  celebrities,
  cities,
  countries,
  animals,
  landmarks,
  planets,
  paintings,
  athletes,
  flowers,
  scientists,
  foods,
  capitals,
  presidents,
  phones,
  films,
  musicArtists,
  tvShows,
  videoGames,
  brands,
  cars,
  dinosaurs,
  birds,
  instruments,
  writers,
  explorers,
  mountains,
  islands,
  inventions,
  dogBreeds,
} from "@/lib/data/entities";

export interface GameTemplate {
  id: string;
  slug: string;
  title: string;
  description: string;
  categoryId: string;
  mode: GameMode;
  difficulty: Difficulty;
  xpReward: number;
  timeLimit?: number;
  maxHints: number;
  maxSkips: number;
  questionPrompt: string;
  entities: EntityEntry[];
  /** Use flag images instead of page thumbnail */
  useFlags?: boolean;
  featured?: boolean;
  trending?: boolean;
  isNew?: boolean;
  /** Max questions per round (subset of entities) */
  questionCount?: number;
}

export const gameTemplates: GameTemplate[] = [
  {
    id: "guess-celebrity",
    slug: "guess-the-celebrity",
    title: "Guess the Celebrity",
    description: "Identify famous people from their photos",
    categoryId: "celebrities",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 55,
    timeLimit: 25,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Who is this celebrity?",
    entities: celebrities,
    featured: true,
    trending: true,
    isNew: true,
    questionCount: 10,
  },
  {
    id: "guess-city",
    slug: "guess-the-city",
    title: "Guess the City",
    description: "Name the city from iconic Wikipedia photos",
    categoryId: "geo",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 50,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Which city is this?",
    entities: cities,
    trending: true,
    isNew: true,
    questionCount: 10,
  },
  {
    id: "guess-flag",
    slug: "guess-the-flag",
    title: "Guess the Flag",
    description: "Identify countries from their flags",
    categoryId: "geo",
    mode: "guess-from-image",
    difficulty: "easy",
    xpReward: 45,
    timeLimit: 20,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Which country does this flag belong to?",
    entities: countries,
    useFlags: true,
    featured: true,
    questionCount: 10,
  },
  {
    id: "guess-animal-wiki",
    slug: "guess-the-animal-wiki",
    title: "Guess the Animal",
    description: "Identify animals from Wikipedia photos",
    categoryId: "animals",
    mode: "guess-from-image",
    difficulty: "easy",
    xpReward: 40,
    maxHints: 3,
    maxSkips: 2,
    questionPrompt: "What animal is this?",
    entities: animals,
    trending: true,
    questionCount: 10,
  },
  {
    id: "guess-landmark-wiki",
    slug: "guess-the-landmark",
    title: "Guess the Landmark",
    description: "Name famous landmarks around the world",
    categoryId: "landmarks",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 50,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "What landmark is this?",
    entities: landmarks,
    questionCount: 8,
  },
  {
    id: "guess-planet",
    slug: "guess-the-planet",
    title: "Guess the Planet",
    description: "Explore our solar system",
    categoryId: "space",
    mode: "guess-from-image",
    difficulty: "easy",
    xpReward: 35,
    maxHints: 3,
    maxSkips: 2,
    questionPrompt: "Which planet is this?",
    entities: planets,
    questionCount: 8,
  },
  {
    id: "guess-painting",
    slug: "guess-the-painting",
    title: "Guess the Painting",
    description: "Identify masterpieces of art history",
    categoryId: "art",
    mode: "guess-from-image",
    difficulty: "hard",
    xpReward: 60,
    maxHints: 1,
    maxSkips: 1,
    questionPrompt: "What is this famous painting called?",
    entities: paintings,
    isNew: true,
    questionCount: 6,
  },
  {
    id: "guess-athlete",
    slug: "guess-the-athlete",
    title: "Guess the Athlete",
    description: "Identify sports legends from photos",
    categoryId: "sports",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 50,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Who is this athlete?",
    entities: athletes,
    trending: true,
    questionCount: 8,
  },
  {
    id: "guess-flower",
    slug: "guess-the-flower",
    title: "Guess the Flower",
    description: "Name flowers from beautiful photos",
    categoryId: "nature",
    mode: "guess-from-image",
    difficulty: "easy",
    xpReward: 35,
    maxHints: 3,
    maxSkips: 2,
    questionPrompt: "What flower is this?",
    entities: flowers,
    questionCount: 8,
  },
  {
    id: "guess-scientist",
    slug: "guess-the-scientist",
    title: "Guess the Scientist",
    description: "Identify history's greatest minds",
    categoryId: "science",
    mode: "guess-from-image",
    difficulty: "hard",
    xpReward: 55,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Who is this scientist?",
    entities: scientists,
    isNew: true,
    questionCount: 6,
  },
  {
    id: "guess-food-wiki",
    slug: "guess-the-food",
    title: "Guess the Food",
    description: "Identify dishes from around the world",
    categoryId: "food",
    mode: "guess-from-image",
    difficulty: "easy",
    xpReward: 40,
    maxHints: 2,
    maxSkips: 2,
    questionPrompt: "What food is this?",
    entities: foods,
    questionCount: 8,
  },
  {
    id: "guess-country",
    slug: "guess-the-country",
    title: "Guess the Country",
    description: "Identify countries from Wikipedia photos",
    categoryId: "geo",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 45,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Which country is this?",
    entities: countries,
    questionCount: 10,
  },
  {
    id: "guess-capital",
    slug: "guess-the-capital",
    title: "Guess the Capital",
    description: "Identify world capital cities from photos",
    categoryId: "geo",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 50,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Which capital city is this?",
    entities: capitals,
    isNew: true,
    trending: true,
    questionCount: 10,
  },
  {
    id: "guess-president",
    slug: "guess-the-president",
    title: "Guess the President",
    description: "Identify world leaders from history and today",
    categoryId: "history",
    mode: "guess-from-image",
    difficulty: "hard",
    xpReward: 55,
    timeLimit: 25,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Who is this president or world leader?",
    entities: presidents,
    featured: true,
    trending: true,
    isNew: true,
    questionCount: 10,
  },
  {
    id: "guess-car",
    slug: "guess-the-car",
    title: "Guess the Car",
    description: "Identify iconic cars from Wikipedia photos",
    categoryId: "cars",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 55,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Which car is this?",
    entities: cars,
    trending: true,
    questionCount: 8,
  },
  {
    id: "guess-phone",
    slug: "guess-the-phone",
    title: "Guess the Phone",
    description: "Identify iconic smartphones from photos",
    categoryId: "phones",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 50,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Which phone is this?",
    entities: phones,
    isNew: true,
    trending: true,
    questionCount: 8,
  },
  {
    id: "guess-movie",
    slug: "guess-the-movie",
    title: "Guess the Movie",
    description: "Name films from posters and scenes",
    categoryId: "movies",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 55,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Which movie is this?",
    entities: films,
    featured: true,
    trending: true,
    questionCount: 8,
  },
  {
    id: "guess-artist",
    slug: "guess-the-artist",
    title: "Guess the Artist",
    description: "Identify musicians from Wikipedia photos",
    categoryId: "music",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 50,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Who is this artist?",
    entities: musicArtists,
    isNew: true,
    questionCount: 8,
  },
  {
    id: "guess-tv-show",
    slug: "guess-the-tv-show",
    title: "Guess the TV Show",
    description: "Name TV series from iconic images",
    categoryId: "tv",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 50,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Which TV show is this?",
    entities: tvShows,
    isNew: true,
    questionCount: 8,
  },
  {
    id: "guess-video-game",
    slug: "guess-the-video-game",
    title: "Guess the Video Game",
    description: "Identify games from screenshots and art",
    categoryId: "games",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 55,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Which video game is this?",
    entities: videoGames,
    featured: true,
    trending: true,
    questionCount: 8,
  },
  {
    id: "guess-brand",
    slug: "guess-the-brand",
    title: "Guess the Brand",
    description: "Identify companies from logos and photos",
    categoryId: "brands",
    mode: "guess-from-image",
    difficulty: "easy",
    xpReward: 45,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Which brand is this?",
    entities: brands,
    trending: true,
    questionCount: 8,
  },
  {
    id: "guess-tech-brand",
    slug: "guess-the-tech-company",
    title: "Guess the Tech Company",
    description: "Identify technology giants from Wikipedia",
    categoryId: "tech",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 50,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Which tech company is this?",
    entities: brands,
    isNew: true,
    questionCount: 8,
  },
  {
    id: "guess-dinosaur",
    slug: "guess-the-dinosaur",
    title: "Guess the Dinosaur",
    description: "Identify prehistoric giants from fossils and art",
    categoryId: "nature",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 45,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Which dinosaur is this?",
    entities: dinosaurs,
    isNew: true,
    trending: true,
    questionCount: 8,
  },
  {
    id: "guess-bird",
    slug: "guess-the-bird",
    title: "Guess the Bird",
    description: "Name birds from around the world",
    categoryId: "animals",
    mode: "guess-from-image",
    difficulty: "easy",
    xpReward: 40,
    maxHints: 2,
    maxSkips: 2,
    questionPrompt: "What bird is this?",
    entities: birds,
    isNew: true,
    questionCount: 8,
  },
  {
    id: "guess-instrument",
    slug: "guess-the-instrument",
    title: "Guess the Instrument",
    description: "Identify musical instruments by sight",
    categoryId: "music",
    mode: "guess-from-image",
    difficulty: "easy",
    xpReward: 40,
    maxHints: 2,
    maxSkips: 2,
    questionPrompt: "Which instrument is this?",
    entities: instruments,
    isNew: true,
    questionCount: 8,
  },
  {
    id: "guess-writer",
    slug: "guess-the-writer",
    title: "Guess the Writer",
    description: "Identify famous authors and poets",
    categoryId: "history",
    mode: "guess-from-image",
    difficulty: "hard",
    xpReward: 55,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Who is this writer?",
    entities: writers,
    isNew: true,
    trending: true,
    questionCount: 8,
  },
  {
    id: "guess-explorer",
    slug: "guess-the-explorer",
    title: "Guess the Explorer",
    description: "Identify history's greatest adventurers",
    categoryId: "history",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 50,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Who is this explorer?",
    entities: explorers,
    isNew: true,
    questionCount: 8,
  },
  {
    id: "guess-mountain",
    slug: "guess-the-mountain",
    title: "Guess the Mountain",
    description: "Name famous peaks and summits",
    categoryId: "geo",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 45,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Which mountain is this?",
    entities: mountains,
    isNew: true,
    questionCount: 8,
  },
  {
    id: "guess-island",
    slug: "guess-the-island",
    title: "Guess the Island",
    description: "Identify islands from stunning photos",
    categoryId: "geo",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 45,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "Which island is this?",
    entities: islands,
    isNew: true,
    questionCount: 8,
  },
  {
    id: "guess-invention",
    slug: "guess-the-invention",
    title: "Guess the Invention",
    description: "Identify breakthroughs that changed the world",
    categoryId: "science",
    mode: "guess-from-image",
    difficulty: "medium",
    xpReward: 50,
    maxHints: 2,
    maxSkips: 1,
    questionPrompt: "What invention is this?",
    entities: inventions,
    isNew: true,
    trending: true,
    questionCount: 8,
  },
  {
    id: "guess-dog-breed",
    slug: "guess-the-dog-breed",
    title: "Guess the Dog Breed",
    description: "Name popular dog breeds from photos",
    categoryId: "animals",
    mode: "guess-from-image",
    difficulty: "easy",
    xpReward: 40,
    maxHints: 2,
    maxSkips: 2,
    questionPrompt: "Which dog breed is this?",
    entities: dogBreeds,
    isNew: true,
    questionCount: 8,
  },
];

export function getTemplateBySlug(slug: string) {
  return gameTemplates.find((t) => t.slug === slug);
}
