/**
 * Curated Wikimedia URLs — used when live Wikipedia fetch misses an image.
 * Keys match entity `wiki` titles (underscores).
 */
export const fallbackImages: Record<string, string> = {
  Leonardo_DiCaprio:
    "https://upload.wikimedia.org/wikipedia/commons/4/46/Leonardo_Dicaprio_Cannes_2019.jpg",
  Taylor_Swift:
    "https://upload.wikimedia.org/wikipedia/commons/b/b5/191125_Taylor_Swift_at_the_2019_American_Music_Awards_%28cropped%29.png",
  Beyonce:
    "https://upload.wikimedia.org/wikipedia/commons/1/17/Beyonc%C3%A9_at_The_Lion_King_European_Premiere_2019.png",
  Tom_Cruise:
    "https://upload.wikimedia.org/wikipedia/commons/4/46/Tom_Cruise_2023.jpg",
  Dwayne_Johnson:
    "https://upload.wikimedia.org/wikipedia/commons/9/9d/Dwayne_Johnson_2014_%28cropped%29.jpg",
  Rihanna:
    "https://upload.wikimedia.org/wikipedia/commons/c/c2/Rihanna_Fenty_2018.png",
  Cristiano_Ronaldo:
    "https://upload.wikimedia.org/wikipedia/commons/8/8c/Cristiano_Ronaldo_2018.jpg",
  Serena_Williams:
    "https://upload.wikimedia.org/wikipedia/commons/4/4b/Serena_Williams_at_2013_US_Open.jpg",
  Barack_Obama:
    "https://upload.wikimedia.org/wikipedia/commons/8/8d/President_Barack_Obama.jpg",
  Oprah_Winfrey:
    "https://upload.wikimedia.org/wikipedia/commons/3/3d/Oprah_Winfrey_2014.jpg",
  Elon_Musk:
    "https://upload.wikimedia.org/wikipedia/commons/3/34/Elon_Musk_Royal_Society_%28crop2%29.jpg",
  Zendaya:
    "https://upload.wikimedia.org/wikipedia/commons/2/28/Zendaya_-_2019_by_Glenn_Francis.jpg",
  Ryan_Reynolds:
    "https://upload.wikimedia.org/wikipedia/commons/1/14/Deadpool_2_Japan_Premiere_Red_Carpet_Ryan_Reynolds_%28cropped%29.jpg",
  Emma_Watson:
    "https://upload.wikimedia.org/wikipedia/commons/7/7f/Emma_Watson_2013.jpg",
  Keanu_Reeves:
    "https://upload.wikimedia.org/wikipedia/commons/9/90/Keanu_Reeves_%28crop_and_levels%29_%28cropped%29.jpg",
  Lady_Gaga:
    "https://upload.wikimedia.org/wikipedia/commons/0/0e/Lady_Gaga_at_Joanne_World_Tour_%28cropped%29.jpg",
  Michael_Jordan:
    "https://upload.wikimedia.org/wikipedia/commons/a/ae/Michael_Jordan_in_2014.jpg",
  Scarlett_Johansson:
    "https://upload.wikimedia.org/wikipedia/commons/2/2a/Scarlett_Johansson-8585.jpg",
  "Robert_Downey_Jr.":
    "https://upload.wikimedia.org/wikipedia/commons/2/23/Robert_Downey_Jr._2014_Comic-Con.jpg",
  Jennifer_Lawrence:
    "https://upload.wikimedia.org/wikipedia/commons/f/fe/Jennifer_Lawrence_in_2018.png",
  George_Washington:
    "https://upload.wikimedia.org/wikipedia/commons/b/b6/Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg",
  Abraham_Lincoln:
    "https://upload.wikimedia.org/wikipedia/commons/a/ab/Abraham_Lincoln_O-77_matte_collodion_print.jpg",
  "Franklin_D._Roosevelt":
    "https://upload.wikimedia.org/wikipedia/commons/4/42/FDR_1944_Color_Portrait.jpg",
  "John_F._Kennedy":
    "https://upload.wikimedia.org/wikipedia/commons/c/c3/John_F._Kennedy%2C_White_House_color_photo_portrait.jpg",
  Joe_Biden:
    "https://upload.wikimedia.org/wikipedia/commons/6/68/Joe_Biden_presidential_portrait.jpg",
  Donald_Trump:
    "https://upload.wikimedia.org/wikipedia/commons/5/56/Donald_Trump_official_portrait.jpg",
  Thomas_Jefferson:
    "https://upload.wikimedia.org/wikipedia/commons/b/b1/Official_Presidential_portrait_of_Thomas_Jefferson_%28by_Rembrandt_Peale%2C_1800%29%28cropped%29.jpg",
  Theodore_Roosevelt:
    "https://upload.wikimedia.org/wikipedia/commons/1/1c/President_Roosevelt_-_Pach_Bros.jpg",
  Ronald_Reagan:
    "https://upload.wikimedia.org/wikipedia/commons/1/16/Official_Portrait_of_President_Reagan_1981.jpg",
  Winston_Churchill:
    "https://upload.wikimedia.org/wikipedia/commons/b/bc/Sir_Winston_Churchill_-_19086236948.jpg",
  Nelson_Mandela:
    "https://upload.wikimedia.org/wikipedia/commons/0/02/Nelson_Mandela_1994.jpg",
  Charles_de_Gaulle:
    "https://upload.wikimedia.org/wikipedia/commons/2/2f/Charles_de_Gaulle-1963.jpg",
  Volodymyr_Zelenskyy:
    "https://upload.wikimedia.org/wikipedia/commons/9/9c/Volodymyr_Zelensky_Official_portrait.jpg",
  Emmanuel_Macron:
    "https://upload.wikimedia.org/wikipedia/commons/7/7e/Emmanuel_Macron_portrait_%28cropped%29.jpg",
  Justin_Trudeau:
    "https://upload.wikimedia.org/wikipedia/commons/8/8a/Justin_Trudeau_2019.jpg",
  "Star_Wars_(film)":
    "https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg",
  The_Godfather:
    "https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg",
  "Titanic_(1997_film)":
    "https://upload.wikimedia.org/wikipedia/en/2/22/Titanic_poster.jpg",
  The_Dark_Knight:
    "https://upload.wikimedia.org/wikipedia/en/8/8a/Dark_Knight.jpg",
  "Jurassic_Park_(film)":
    "https://upload.wikimedia.org/wikipedia/en/e/e7/Jurassic_Park_poster.jpg",
  Forrest_Gump:
    "https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg",
  The_Lion_King:
    "https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg",
  "Avatar_(2009_film)":
    "https://upload.wikimedia.org/wikipedia/en/d/d6/Avatar_%282009_film%29_poster.jpg",
  Inception:
    "https://upload.wikimedia.org/wikipedia/en/7/7f/Inception_ver3.jpg",
  The_Matrix:
    "https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg",
};

export function getFallbackImage(wikiTitle: string): string | undefined {
  return fallbackImages[wikiTitle];
}
